CREATE TABLE public.da_admn (
    admn_no character varying(15) NOT NULL,
    admn_dt timestamp without time zone,
    umr_no character varying(15),
    er_no character varying(15),
    er_dt timestamp without time zone,
    trn_source_cd character varying,
    er_case_type_cd character varying,
    area_cd character varying(8),
    city_cd character varying(8),
    district_cd character varying(8),
    state_cd character varying(8),
    country_cd character varying(8),
    age character varying(4000),
    company_cd character varying(8),
    company_type_cd character varying(15),
    admission_type_cd character varying(8),
    department_cd character varying(8),
    doctor_cd character varying(8),
    ward_cd character varying(8),
    room_cd character varying(15),
    rec_type_cd character varying(1),
    loc_cd character varying(15),
    org_cd character varying(8) NOT NULL,
    grp_cd character varying(8) NOT NULL,
    record_status character(1),
    dw_last_updated_dt timestamp without time zone,
    dw_facility_cd character varying(16),
    dw_job_run_no numeric,
    dw_row_id character varying(128)
);
