
CREATE TABLE public.da_reg (
    reg_no character varying(15) NOT NULL,
    reg_dt timestamp without time zone,
    umr_no character varying(15),
    area_cd character varying(8),
    city_cd character varying(8),
    district_cd character varying(8),
    state_cd character varying(8),
    country_cd character varying(8),
    referal_source_cd character(1),
    nationality_cd character varying(32),
    expiry_dt timestamp without time zone,
    is_expired character(1),
    trn_source_cd character varying,
    company_cd character varying(8),
    company_type_cd character varying(15),
    rec_type_cd character varying(1),
    record_status character(1),
    loc_cd character varying(15),
    org_cd character varying(8) NOT NULL,
    grp_cd character varying(8) NOT NULL,
    dw_last_updated_dt timestamp without time zone,
    dw_facility_cd character varying(16),
    dw_job_run_no numeric,
    dw_row_id character varying(128),
    age character varying(16)
);
