CREATE TABLE public.dl_fact_registration (
    dw_row_id character varying(128),
    umr_no character varying(15),
    patient_name character varying(96),
    gender_cd character(1),
    gender_name character varying(32),
    dob timestamp without time zone,
    age character varying(16),
    reg_no character varying(15),
    reg_dt timestamp without time zone,
    referal_source_cd character(1),
    referal_source_name character varying(17),
    area_cd character varying(8),
    area_name character varying(64),
    city_cd character varying(8),
    city_name character varying(64),
    district_cd character varying(8),
    district_name character varying(64),
    state_cd character varying(8),
    state_name character varying(64),
    country_cd character varying(8),
    country_name character varying(64),
    nationality_cd character varying(32),
    nationality_name character varying(32),
    company_cd character varying(8),
    company_name character varying(60),
    company_type_cd character varying(15),
    company_type_name character varying(64),
    expiry_dt timestamp without time zone,
    is_expired character(1),
    trn_source_cd character varying,
    trn_source_name character varying(64),
    rec_type_cd character varying(1),
    rec_type_name character(5),
    record_status character(1),
    loc_cd character varying(64),
    loc_name character varying(128),
    loc_short_name character varying(16),
    org_cd character varying(8),
    org_name character varying(128),
    org_short_name character varying(16),
    grp_cd character varying(8),
    grp_name character varying(64),
    grp_short_name character varying(16),
    age_in_years integer,
    age_in_months integer,
    age_in_days integer,
    dw_facility_cd character varying(16),
    dw_job_run_no numeric,
    dw_last_updated_dt timestamp without time zone
);
