CREATE TABLE da_admn (
    admn_no varchar2(15) NOT NULL,
    admn_dt date,
    umr_no varchar2(15),
    er_no varchar2(15),
    er_dt date,
    trn_source_cd varchar2,
    er_case_type_cd varchar2,
    area_cd varchar2(8),
    city_cd varchar2(8),
    district_cd varchar2(8),
    state_cd varchar2(8),
    country_cd varchar2(8),
    age varchar2(4000),
    company_cd varchar2(8),
    company_type_cd varchar2(15),
    admission_type_cd varchar2(8),
    department_cd varchar2(8),
    doctor_cd varchar2(8),
    ward_cd varchar2(8),
    room_cd varchar2(15),
    rec_type_cd varchar2(1),
    loc_cd varchar2(15),
    org_cd varchar2(8) NOT NULL,
    grp_cd varchar2(8) NOT NULL,
    record_status char(1),
    dw_last_updated_dt date,
    dw_facility_cd varchar2(16),
    dw_job_run_no INTEGER,
    dw_row_id varchar2(128)
);
