
CREATE TABLE da_consultation (
    umr_no varchar2(15),
    age varchar2(16),
    bill_no varchar2(15),
    bill_dt date,
    tran_no varchar2(15),
    tran_dt date,
    bill_type_cd varchar2(33),
    doctor_cd varchar2(15),
    speciality_cd varchar2(8),
    company_cd varchar2(8),
    company_type_cd varchar2(15),
    rec_type_cd varchar2(1),
    consultation_type_cd varchar2(9),
    appointment_type_cd varchar2,
    service_cd varchar2,
    quantity number,
    rate number,
    amount number,
    discount_amount number,
    receipt_amount number,
    area_cd varchar2(8),
    city_cd varchar2(8),
    district_cd varchar2(8),
    state_cd varchar2(8),
    country_cd varchar2(8),
    loc_cd varchar2(15),
    org_cd varchar2(8),
    grp_cd varchar2(8),
    dw_last_updated_dt date,
    dw_facility_cd varchar2(16),
    dw_job_run_no integer,
    dw_row_id varchar2(128)
);

