CREATE TABLE etl_job_step
(
    job_cd  varchar(256) NOT NULL,
    job_step_cd  varchar(256) NOT NULL,
    job_step_name  varchar(256) ,
    job_step_desc  varchar(512),
    job_step_seq integer,
    job_program_cd  varchar(256) ,
    job_program_action  varchar(1000),
	Job_program_arg1  varchar(1000),
    Job_program_arg2  varchar(1000),
	Job_program_arg3  varchar(1000),
	Job_program_arg4  varchar(1000),
	Job_program_arg5  varchar(1000),
	Job_program_arg6  varchar(1000),
	Job_program_arg7  varchar(1000),
	Job_program_arg8  varchar(1000),
	Job_program_arg9  varchar(1000),
	Job_program_arg10  varchar(1000),
	job_on_error  varchar(256) ,
    last_run_status  varchar(256)  ,
    last_run_start_dt  timestamp ,
    last_run_end_dt  timestamp ,
    last_run_duration varchar(36) ,
    last_success_run_dt  timestamp ,
    record_status  varchar(1) ,
    create_by  varchar(256) ,
    create_dt  timestamp ,
    modify_by  varchar(256) ,
    modify_dt  timestamp ,
    loc_cd  varchar(16) ,
    org_cd  varchar(16) ,
    grp_cd  varchar(16)  NOT NULL
   
)