  CREATE VIEW TZ_ETL_JOB_SCHSCH AS
SELECT 	J.SCH_CD , 
	J.SCH_NAME , 
	J.SCH_DESC , 
	J.SCH_START_DT + TZ.UTC_minutes * INTERVAL '1 minute' as SCH_START_DT , 
	J.SCH_END_DT + TZ.UTC_minutes * INTERVAL '1 minute' as SCH_END_DT , 
	J.SCH_MINUTE , 
	J.SCH_HOUR , 
	J.SCH_DAY_OF_MONTH , 
	J.SCH_MONTH_OF_YEAR , 
	J.SCH_DAY_OF_WEEK , 
	J.RECORD_STATUS , 
	J.CREATE_BY , 
	J.CREATE_DT + TZ.UTC_minutes * INTERVAL '1 minute' as CREATE_DT , 
	J.MODIFY_BY , 
	J.MODIFY_DT + TZ.UTC_minutes * INTERVAL '1 minute' as MODIFY_DT, 
	J.LOC_CD , 
	J.ORG_CD , 
	J.GRP_CD 
FROM ETL_JOB_SCHSCH J 
CROSS JOIN  ETL_TIMEZONE TZ