 CREATE VIEW TZ_ETL_JOB_PROGRAM AS
   SELECT J.JOB_PROGRAM_CD , 
	J.JOB_PROGRAM_NAME , 
	J.JOB_PROGRAM_DESC , 
	J.RECORD_STATUS , 
	J.CREATE_BY , 
	J.CREATE_DT + TZ.UTC_minutes * INTERVAL '1 minute' as CREATE_DT, 
	J.MODIFY_BY , 
	J.MODIFY_DT + TZ.UTC_minutes * INTERVAL '1 minute' as MODIFY_DT , 
	J.ORG_CD , 
	J.LOC_CD , 		
	J.GRP_CD 
   FROM  ETL_JOB_PROGRAM J
   CROSS JOIN  ETL_TIMEZONE TZ 