
  CREATE VIEW TZ_ETL_JOB_ERROR_LOG AS 
   SELECT J.JOB_ERROR_LOG_ID , 
	J.JOB_STEP_LOG_ID , 
	J.JOB_LOG_ID , 
	J.JOB_STEP_CD , 
	J.JOB_GROUP_CD , 
	J.JOB_CD , 
	J.JOB_RUN_NO , 
	J.ERROR_SOURCE , 
	J.ERROR_TYPE_CD , 
	J.ERROR_CD , 
	J.ERROR_MESSAGE , 
	J.ERROR_DT + TZ.UTC_minutes/1440 as ERROR_DT , 
	J.ERROR_INFO1 , 
	J.ERROR_INFO2 , 
	J.ERROR_INFO3 , 
	J.RECORD_STATUS , 
	J.CREATE_BY , 
	J.CREATE_DT + TZ.UTC_minutes/1440 as CREATE_DT , 
	J.MODIFY_BY , 
	J.MODIFY_DT + TZ.UTC_minutes/1440 as MODIFY_DT , 
	J.ORG_CD , 
	J.LOC_CD , 
	J.GRP_CD 
 FROM ETL_JOB_ERROR_LOG  J
 CROSS JOIN  ETL_TIMEZONE TZ 

