  CREATE VIEW TZ_ETL_JOB_PROGRAM_ACTION AS
  SELECT J.JOB_PROGRAM_ACTION_CD , 
	J.JOB_PROGRAM_ACTION_NAME , 
	J.JOB_PROGRAM_ACTION_DESC , 
	J.RECORD_STATUS , 
	J.CREATE_BY , 
	J.CREATE_DT + TZ.UTC_minutes/1440 as CREATE_DT, 
	J.MODIFY_BY , 
	J.MODIFY_DT + TZ.UTC_minutes/1440 as MODIFY_DT, 
	J.ORG_CD , 
	J.LOC_CD , 
	J.GRP_CD 
 FROM ETL_JOB_PROGRAM_ACTION  J  
 CROSS JOIN  ETL_TIMEZONE TZ
